### ISSUE TITLE
Creating a first dApp

### ISSUE THREAD

**Issue by zhangpn** [DZhangLab/HIDe-dApp#17]
Follow this tutorial to set up a dApp using Fabric. The outcome of this issue is to:
- [ ] gain familiarity with what a basic dApp setup looks like 
- [ ] create a boilerplate https://mycoralhealth.medium.com/build-a-dapp-on-hyperledger-the-easy-way-178c39e503fa or follow this link: https://hyperledger-fabric.readthedocs.io/en/release-1.4/write_first_app.html
- [ ] A page/paragraph documenting the 'setup' of the dApp, including what environment this was developed/tested in and tests created
- [ ] Smart contract - @katherinehuu 
- [ ] Create the app interface to call the smart contract - @Pei-Shan-Tan

**Comment by katherinehuu** [comment]
Failed commands
1. [Tutorial 1](https://mycoralhealth.medium.com/start-your-own-hyperledger-blockchain-the-easy-way-5758cb4ed2d1):
> peer chaincode instantiate -o orderer.example.com:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem -C $CHANNEL_NAME -n mycc -v 1.0 -c '{"Args":["init","a", "100", "b","200"]}' -P "OR ('Org1MSP.peer','Org2MSP.peer')"
2. [Tutorial 2](https://mycoralhealth.medium.com/build-a-dapp-on-hyperledger-the-easy-way-178c39e503fa): 
> docker rm -f $(docker ps -aq)
3. [Tutorial 2](https://mycoralhealth.medium.com/build-a-dapp-on-hyperledger-the-easy-way-178c39e503fa): 
> npm install
4. [Tutorial 2](https://mycoralhealth.medium.com/build-a-dapp-on-hyperledger-the-easy-way-178c39e503fa): 
> node enrollAdmin.js

Error message for #3:
node-gyp rebuild || node suppress-error.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at ‘/‘.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
gyp: No Xcode or CLT version detected!
