### ISSUE TITLE
Authentication step, permissioned users stored in verifier and then allowed to insert into registry

### ISSUE THREAD

**Issue by mchales** [DZhangLab/HIDe-dApp#34]
This user should meet both checks as follows (for now):
1) user's DID is a Verifier role (i.e., DID exists in the Verifier registry)
2) user's public key and private key should match (public key should be created with the DID as a separate key pair - just assume this has already been done for now and feel free to [generate](https://walletgenerator.net/) or use an existing pub/key pair)

**Comment by mchales** [comment]
Use RegistryController.sol

**Comment by ebenissan** [comment]
@sean-the-coder close if done
